In [3]:
import numpy as np

In [5]:
my_list1 = [1, 2, 3, 4]  

In [10]:
my_array1 = np.array(my_list1)

In [11]:
print(my_array1)

[1 2 3 4]


In [12]:
my_list2 = [11, 12, 13, 14]

In [13]:
my_lists = [my_list1, my_list2]

In [14]:
my_array2 = np.array(my_lists)

In [15]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14]])

In [16]:
my_array2.dtype

dtype('int64')

In [17]:
my_array2.shape

(2, 4)

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
my_zeros_array = np.zeros(5)

In [20]:
my_zeros_array.dtype

dtype('float64')

In [22]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [28]:
np.arange(3, 38, 3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36])

In [29]:
5/2

2.5

In [34]:
# array and scalers
arr1 = np.array([[1, 2, 3, 4],[8, 9, 10, 11]])

In [35]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [36]:
arr1 * arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [37]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [38]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]])

In [39]:
# indexing arrays
arr2 = np.arange(0, 11)

In [40]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr2[8]

8

In [42]:
arr2[0:5]

array([0, 1, 2, 3, 4])

In [43]:

arr2[4:7]

array([4, 5, 6])

In [44]:
arr2[0:5] = 100

In [45]:
arr2


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [46]:
arr = np.arange(0, 11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
slice_of_arr = arr[0:6]

In [49]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [50]:
slice_of_arr[:] = 99

In [51]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [52]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])